### ISSUE TITLE
Exception on OS X

### ISSUE THREAD

**Issue by jasim** [giraud/reasonml-idea-plugin#2]
(Thanks a lot for making this!)

Error: "Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())"

Steps to reproduce: Install the plugin, change the VM settings as per documentation, restart the IDE.

I'm use RubyMine. After the plugin is installed, syntax highlighting works. And the types are displayed if the file doesn't have any errors. If I make a type error, the types go away, but no error underlining is shown. The IDE also hangs but I'm not sure when or why. I understand this is in very early stages of development. If you get it working I'd be happy to use as a commercial project.

Here is the error trace for the above message:

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[JobScheduler FJ pool 0/8,4,main] 468544714
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.1.1#RM-171.4073.39 RubyMine, eap:false, os:Mac OS X 10.12.4, java-version:JetBrains s.r.o 1.8.0_112-release-736-b16,6,main] 1582051056
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1068)
	at com.intellij.psi.impl.source.tree.TreeElement.getStartOffsetInParent(TreeElement.java:130)
	at com.intellij.psi.impl.source.tree.TreeElement.getStartOffset(TreeElement.java:118)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getTextOffset(ASTDelegatePsiElement.java:142)
	at com.reason.ide.hints.ReasonMLEditorLinePainter.lambda$getLineExtensions$0(ReasonMLEditorLinePainter.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:285)
	at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by giraud** [comment]
Thanks jasim.

The freeze is a bug in the code that call refmt, you should try with version 0.7 of the plugin, it should be fixed (I don't have OSX to confirm).

I'm working on the exception but I'm not sure how to do things yet.
